language: php

php:
  - 5.5
  - 5.4

before_script:
  - make install
  - bin/composer.phar install --dev
  - mkdir '.coverage/'

script: bin/phpunit

after_script:
  - bin/coveralls -c '../.coveralls.yml'
